name: Node.js CI
on:
  push:
    branch: [main]
  # on: [push, workflow_dispatch, ...]  # Multiple workflow triggers can be added here
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Testing against multiple Node.js versions
    steps:
      - name: Get code
        uses: actions/checkout@v4  # Predefined action to check out code from the repository
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4  # Predefined action to set up Node.js
        with:
          node-version: ${{ matrix.node-version }}  # Matrix variable for Node.js version
      - name: Install dependencies
        run: npm ci  # Running shell command to install dependencies
      - name: Build project (if present)
        run: npm run build --if-present  # Running shell command to build the project if build script exists
      - name: Test application
        run: npm test  # Running shell command to run tests