name: Node.js CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.17.0]  # Specify the Node.js version to use
    steps:
      - name: Get code
        uses: actions/checkout@v4  # Check out the code from the repository

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4  # Set up Node.js environment
        with:
          node-version: ${{ matrix.node-version }}  # Use the specified Node.js version

      - name: Install npm
        run: npm install -g npm  # Install the latest npm globally

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Build project (if present)
        run: npm run build --if-present  # Build the project only if a build script is present

      # Skip the test step if no tests are present
      - name: Skip test if not available
        run: |
          if [ -f package.json ] && grep -q '"test":' package.json; then
            npm test;
          else
            echo "No test script found, skipping tests.";
          fi
